/**
 * UI Store
 * i18n 用 computed signal 确保语言切换触发重渲染
 */
import { signal, computed } from '@preact/signals';

export const theme = signal<'dark' | 'light'>('dark');
export const lang = signal<'zh' | 'en'>('zh');
export const toasts = signal<{ id: string; message: string; type: string }[]>([]);

export function initUI() {
  const savedTheme = localStorage.getItem('oasyce-theme') as 'dark' | 'light' | null;
  const savedLang = localStorage.getItem('oasyce-lang') as 'zh' | 'en' | null;

  theme.value = savedTheme || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
  lang.value = savedLang || (navigator.language?.startsWith('zh') ? 'zh' : 'en');

  document.documentElement.setAttribute('data-theme', theme.value);
}

export function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
  document.documentElement.setAttribute('data-theme', theme.value);
  localStorage.setItem('oasyce-theme', theme.value);
}

export function toggleLang() {
  lang.value = lang.value === 'zh' ? 'en' : 'zh';
  localStorage.setItem('oasyce-lang', lang.value);
}

export function showToast(message: string, type = 'info') {
  const id = Date.now().toString();
  toasts.value = [...toasts.value, { id, message, type }];
  setTimeout(() => toasts.value = toasts.value.filter(t => t.id !== id), 3000);
}

const dict: Record<string, Record<string, string>> = {
  zh: {
    home: '首页', mydata: '资产', explore: '探索', auto: '自动化', network: '网络',
    'hero-title-light': '数据的权利',
    'hero-title-bold': '由你掌控',
    'hero-sub': '注册、追踪、清算。你的数据在 Oasyce 网络上拥有不可篡改的身份。',
    protect: '注册数据', protecting: '注册中...', protected: '已注册',
    'drop-hint': '拖入文件', 'drop-browse': '选择文件',
    'describe': '描述', 'describe-hint': '例如：医疗影像、研究数据、创意作品',
    'value': '当前价值', 'owner': '所有者', 'id': '编号',
    'search': '搜索你的数据...', 'no-data': '还没有数据', 'first-data': '注册你的第一份数据',
    'delete': '移除', 'delete-confirm': '确定移除这份数据？移除后无法恢复。',
    'get-access': '获取访问权', 'quote': '查看报价', 'quoting': '计算中...',
    'pay': '需要支付', 'receive': '获得份额', 'impact': '价格影响',
    'confirm-buy': '确认获取', 'buying': '处理中...', 'back': '返回',
    'paste-id': '粘贴数据编号', 'amount': '金额',
    'identity': '你的身份', 'identity-hint': '这是你在网络上的唯一标识',
    'no-key': '首次注册数据时自动生成', 'copy': '复制', 'copied': '已复制',
    'advanced': '详细信息',
    'again': '继续注册',
    'nav-mydata': '资产', 'nav-mydata-desc': '查看已注册的数据资产',
    'nav-explore': '探索', 'nav-explore-desc': '搜索网络上的数据资产',
    'nav-network': '网络', 'nav-network-desc': '节点状态与网络信息',
    'cancel': '取消', 'confirm-remove': '确认移除',
    'get-desc': '输入数据编号，查看报价并获取访问权',
    'explore-title': '探索数据',
    'explore-desc': '发现网络上的数据资产，获取访问权',
    'explore-search': '搜索数据编号或描述...',
    'explore-empty': '输入编号或关键词开始搜索',
    'categories': '分类',
    'browse-all': '浏览全部',
    'all': '全部',
    'sort-time': '最新', 'sort-value': '价值',
    'load-more': '加载更多', 'no-more': '没有更多了',
    'view-mydata': '查看资产',
    'type-all': '全部', 'type-data': '数据', 'type-capability': '服务',
    'invoke': '调用', 'invoking': '调用中...',
    'invoke-success': '调用成功',
    'provider': '提供者', 'version': '版本',
    'shares-minted': '获得份额',
    'spot-price': '当前价格', 'tags': '标签', 'type': '类型', 'asset-type-data': '数据', 'asset-type-cap': '服务',
    'total-cost': '总花费', 'shares-received': '获得份额', 'price-impact': '价格影响', 'fees': '手续费',
    'creator-fee': '创作者', 'protocol-fee': '协议', 'router-fee': '路由',
    'buy-success': '购买成功', 'new-price': '新价格', 'shares-bought': '购得份额',
    'portfolio': '持仓', 'no-holdings': '暂无持仓', 'avg-price': '均价', 'shares': '份额', 'current-val': '当前价值',
    'stake': '质押', 'staking': '质押中...', 'stake-success': '质押成功',
    'validator': '验证者', 'staked': '已质押', 'reputation': '信誉',
    'validator-id': '验证者 ID', 'stake-amount': '质押金额',
    'no-validators': '暂无验证者',
    'net-hero-light': '你的', 'net-hero-bold': '网络身份',
    'net-hero-sub': '所有注册与交易都用此身份签名',
    'net-identity': '身份', 'net-node-id': '节点 ID', 'net-pubkey': '公钥', 'net-created': '创建时间',
    'net-no-identity': '尚未生成身份', 'net-init-hint': '运行 oasyce start 来初始化节点',
    'net-watermark': '水印工具', 'net-watermark-desc': '追踪数据在网络中的流转',
    'net-embed': '嵌入水印', 'net-embed-desc': '把身份信息刻进文件',
    'net-extract': '提取水印', 'net-extract-desc': '读出文件的签名信息',
    'net-trace': '追踪分发', 'net-trace-desc': '查看文件的流转记录',
    'identity-card-title': '节点身份',
    'identity-desc': '这是你在 Oasyce 网络上的唯一身份。公钥用于签名交易和验证所有权。',
    'node-id': '节点 ID',
    'created-at': '创建时间',
    'public-key': '公钥',
    'no-identity': '尚未生成身份。运行 oasyce start 来初始化节点。',
    'watermark': '水印工具',
    'wm-embed': '嵌入',
    'wm-extract': '提取',
    'wm-trace': '追踪',
    'wm-file-path': '文件路径',
    'wm-caller-id': '调用者 ID',
    'wm-embed-btn': '嵌入水印',
    'wm-embedding': '嵌入中...',
    'wm-extract-btn': '提取水印',
    'wm-extracting': '提取中...',
    'wm-asset-id': '资产编号',
    'wm-list-btn': '查询分发记录',
    'wm-listing': '查询中...',
    'wm-fingerprint': '指纹',
    'wm-caller': '调用者',
    'wm-timestamp': '时间',
    'wm-watermarked-path': '水印文件',
    'wm-no-records': '暂无分发记录',
    'validators': '验证者',
    'val-staked': '质押量',
    'val-reputation': '信誉',
    'scanner-desc': '扫描本地目录，自动发现可注册的数据资产',
    'automation': '自动化', 'automation-desc': '管理自动注册与交易规则，审批待确认任务',
    'auto-queue': '任务队列', 'auto-rules': '规则设置',
    'pending-tasks': '待确认', 'completed-tasks': '已完成',
    'approve-all': '全部通过', 'all-approved': '已全部通过',
    'queue-empty': '没有待处理任务', 'queue-empty-hint': '扫描目录或等待 Agent 提交新任务',
    'trust-level-desc': '控制 Agent 的自主注册和交易权限',
    'trust-0-desc': '所有操作需手动确认',
    'trust-1-desc': '高置信度自动执行，其余需确认',
    'trust-2-desc': '全部自动执行，仅异常需确认',
    'auto-threshold-desc': '置信度高于阈值的任务将自动通过',
    'threshold-strict': '严格', 'threshold-strict-desc': '仅极高置信度自动通过，大部分需确认',
    'threshold-balanced': '均衡', 'threshold-balanced-desc': '多数可信任务自动通过，可疑任务需确认',
    'threshold-permissive': '宽松', 'threshold-permissive-desc': '大部分任务自动通过，仅低置信度需确认',
    'scan-directory': '扫描目录', 'scan-directory-desc': '扫描本地文件夹，发现可注册的数据资产',
    'agent-executor': '执行 Agent', 'agent-executor-desc': '选择执行注册和交易任务的 Agent',
    'agent-connected': '已连接', 'agent-available': '可用', 'agent-unavailable': '不可用',
    'custom-agent-config': '配置自定义 Agent',
    'custom-agent-name': 'Agent 名称',
    'custom-agent-endpoint': 'API 端点 (例如 https://api.example.com/v1)',
    'custom-agent-test': '测试连接',
    'agent-setup-hint': '需要先在本地安装并配置该 Agent，才能用于自动化任务。',
    'scan-path-hint': '输入目录路径，例如 ~/Documents',
    'scan-btn': '扫描', 'scanning': '扫描中...',
    'scan-done': '扫描完成', 'scan-found': '扫描文件', 'scan-added': '加入收件箱',
    'trust-settings': '信任设置', 'trust-level': '信任等级',
    'trust-0': '手动确认', 'trust-1': '半自动', 'trust-2': '全自动',
    'auto-threshold': '自动确认阈值',
    'inbox': '收件箱', 'inbox-empty': '收件箱为空，扫描目录开始发现资产',
    'inbox-no-match': '没有匹配的项目',
    'filter-all': '全部', 'filter-pending': '待确认', 'filter-approved': '已通过', 'filter-rejected': '已拒绝',
    'confidence': '置信度',
    'status-pending': '待确认', 'status-approved': '已通过', 'status-rejected': '已拒绝',
    'approve': '通过', 'reject': '拒绝', 'edit': '编辑', 'save': '保存',
    'approved': '已通过', 'rejected': '已拒绝', 'saved': '已保存',
    'edit-name': '资产名称', 'edit-tags': '标签（逗号分隔）', 'edit-desc': '描述',
  },
  en: {
    home: 'Home', mydata: 'My Data', explore: 'Explore', auto: 'Automation', network: 'Network',
    'hero-title-light': 'Data rights,',
    'hero-title-bold': 'settled.',
    'hero-sub': 'Register. Track. Clear. Your data gets an immutable identity on the Oasyce network.',
    protect: 'Register', protecting: 'Registering...', protected: 'Registered',
    'drop-hint': 'Drop file', 'drop-browse': 'choose file',
    'describe': 'Description', 'describe-hint': 'e.g. medical imaging, research data, creative work',
    'value': 'Value', 'owner': 'Owner', 'id': 'ID',
    'search': 'Search your data...', 'no-data': 'No data yet', 'first-data': 'Register your first file',
    'delete': 'Remove', 'delete-confirm': 'Remove this data? This cannot be undone.',
    'get-access': 'Get access', 'quote': 'Get quote', 'quoting': 'Calculating...',
    'pay': 'You pay', 'receive': 'You receive', 'impact': 'Price impact',
    'confirm-buy': 'Confirm', 'buying': 'Processing...', 'back': 'Back',
    'paste-id': 'Paste data ID', 'amount': 'Amount',
    'identity': 'Your identity', 'identity-hint': 'Your unique ID on the network',
    'no-key': 'Auto-generated on first registration', 'copy': 'Copy', 'copied': 'Copied',
    'advanced': 'Details',
    'again': 'Register another',
    'nav-mydata': 'My data', 'nav-mydata-desc': 'View your registered data assets',
    'nav-explore': 'Explore', 'nav-explore-desc': 'Search data assets on the network',
    'nav-network': 'Network', 'nav-network-desc': 'Node status and network info',
    'cancel': 'Cancel', 'confirm-remove': 'Confirm remove',
    'get-desc': 'Enter a data ID to get a quote and gain access',
    'explore-title': 'Explore data',
    'explore-desc': 'Discover data assets on the network and get access',
    'explore-search': 'Search by ID or description...',
    'explore-empty': 'Enter an ID or keyword to start',
    'categories': 'Categories',
    'browse-all': 'Browse all',
    'all': 'All',
    'sort-time': 'Latest', 'sort-value': 'Value',
    'load-more': 'Load more', 'no-more': "That's all",
    'view-mydata': 'View my data',
    'type-all': 'All', 'type-data': 'Data', 'type-capability': 'Services',
    'invoke': 'Invoke', 'invoking': 'Invoking...',
    'invoke-success': 'Invoked successfully',
    'provider': 'Provider', 'version': 'Version',
    'shares-minted': 'Shares minted',
    'spot-price': 'Spot price', 'tags': 'Tags', 'type': 'Type', 'asset-type-data': 'Data', 'asset-type-cap': 'Service',
    'total-cost': 'Total cost', 'shares-received': 'Shares received', 'price-impact': 'Price impact', 'fees': 'Fees',
    'creator-fee': 'Creator', 'protocol-fee': 'Protocol', 'router-fee': 'Router',
    'buy-success': 'Purchase successful', 'new-price': 'New price', 'shares-bought': 'Shares bought',
    'portfolio': 'Portfolio', 'no-holdings': 'No holdings yet', 'avg-price': 'Avg price', 'shares': 'Shares', 'current-val': 'Current value',
    'stake': 'Stake', 'staking': 'Staking...', 'stake-success': 'Staked successfully',
    'validator': 'Validator', 'staked': 'Staked', 'reputation': 'Reputation',
    'validator-id': 'Validator ID', 'stake-amount': 'Stake amount',
    'no-validators': 'No validators yet',
    'net-hero-light': 'Your', 'net-hero-bold': 'Network Identity',
    'net-hero-sub': 'Every registration and transaction is signed with this identity',
    'net-identity': 'IDENTITY', 'net-node-id': 'Node ID', 'net-pubkey': 'Public Key', 'net-created': 'Created',
    'net-no-identity': 'No identity yet', 'net-init-hint': 'Run oasyce start to initialize your node',
    'net-watermark': 'WATERMARK TOOLS', 'net-watermark-desc': 'Track data distribution across the network',
    'net-embed': 'Embed watermark', 'net-embed-desc': 'Sign your identity into a file',
    'net-extract': 'Extract watermark', 'net-extract-desc': 'Read signature info from a file',
    'net-trace': 'Trace distribution', 'net-trace-desc': 'View file distribution history',
    'identity-card-title': 'Node Identity',
    'identity-desc': 'This is your unique identity on the Oasyce network. Your public key is used to sign transactions and verify ownership.',
    'node-id': 'Node ID',
    'created-at': 'Created',
    'public-key': 'Public Key',
    'no-identity': 'No identity yet. Run oasyce start to initialize your node.',
    'watermark': 'Watermark Tools',
    'wm-embed': 'Embed',
    'wm-extract': 'Extract',
    'wm-trace': 'Trace',
    'wm-file-path': 'File path',
    'wm-caller-id': 'Caller ID',
    'wm-embed-btn': 'Embed watermark',
    'wm-embedding': 'Embedding...',
    'wm-extract-btn': 'Extract watermark',
    'wm-extracting': 'Extracting...',
    'wm-asset-id': 'Asset ID',
    'wm-list-btn': 'List distributions',
    'wm-listing': 'Loading...',
    'wm-fingerprint': 'Fingerprint',
    'wm-caller': 'Caller',
    'wm-timestamp': 'Time',
    'wm-watermarked-path': 'Watermarked file',
    'wm-no-records': 'No distribution records',
    'validators': 'Validators',
    'val-staked': 'Staked',
    'val-reputation': 'Reputation',
    'scanner-desc': 'Scan local directories to discover registerable data assets',
    'automation': 'Automation', 'automation-desc': 'Manage auto-registration and trading rules, review pending tasks',
    'auto-queue': 'Queue', 'auto-rules': 'Rules',
    'pending-tasks': 'Pending', 'completed-tasks': 'Completed',
    'approve-all': 'Approve all', 'all-approved': 'All approved',
    'queue-empty': 'No pending tasks', 'queue-empty-hint': 'Scan a directory or wait for agents to submit tasks',
    'trust-level-desc': 'Control how much autonomy agents have for registration and trading',
    'trust-0-desc': 'All actions require manual approval',
    'trust-1-desc': 'High-confidence actions auto-execute, rest need approval',
    'trust-2-desc': 'All actions auto-execute, only anomalies flagged',
    'auto-threshold-desc': 'Tasks above the threshold are auto-approved',
    'threshold-strict': 'Strict', 'threshold-strict-desc': 'Only very high confidence auto-approved, most need review',
    'threshold-balanced': 'Balanced', 'threshold-balanced-desc': 'Most trusted tasks auto-approved, suspicious ones flagged',
    'threshold-permissive': 'Permissive', 'threshold-permissive-desc': 'Most tasks auto-approved, only low confidence flagged',
    'scan-directory': 'Scan Directory', 'scan-directory-desc': 'Scan local folders to discover registerable data assets',
    'agent-executor': 'Agent Executor', 'agent-executor-desc': 'Choose which agent handles registration and trading tasks',
    'agent-connected': 'Connected', 'agent-available': 'Available', 'agent-unavailable': 'Unavailable',
    'custom-agent-config': 'Configure Custom Agent',
    'custom-agent-name': 'Agent name',
    'custom-agent-endpoint': 'API endpoint (e.g. https://api.example.com/v1)',
    'custom-agent-test': 'Test connection',
    'agent-setup-hint': 'Install and configure this agent locally before using it for automation.',
    'scan-path-hint': 'Enter directory path, e.g. ~/Documents',
    'scan-btn': 'Scan', 'scanning': 'Scanning...',
    'scan-done': 'Scan complete', 'scan-found': 'Files scanned', 'scan-added': 'Added to inbox',
    'trust-settings': 'Trust Settings', 'trust-level': 'Trust Level',
    'trust-0': 'Manual', 'trust-1': 'Semi-auto', 'trust-2': 'Full-auto',
    'auto-threshold': 'Auto-approve threshold',
    'inbox': 'Inbox', 'inbox-empty': 'Inbox empty. Scan a directory to discover assets.',
    'inbox-no-match': 'No matching items',
    'filter-all': 'All', 'filter-pending': 'Pending', 'filter-approved': 'Approved', 'filter-rejected': 'Rejected',
    'confidence': 'Confidence',
    'status-pending': 'Pending', 'status-approved': 'Approved', 'status-rejected': 'Rejected',
    'approve': 'Approve', 'reject': 'Reject', 'edit': 'Edit', 'save': 'Save',
    'approved': 'Approved', 'rejected': 'Rejected', 'saved': 'Saved',
    'edit-name': 'Asset name', 'edit-tags': 'Tags (comma separated)', 'edit-desc': 'Description',
  },
};

/**
 * i18n computed — 返回一个 computed signal
 * 组件里用 i18n.value['key'] 来读取，确保 signal tracking
 */
export const i18n = computed(() => dict[lang.value] || dict['en']);
