/**
 * UI Store
 * i18n 用 computed signal 确保语言切换触发重渲染
 */
import { signal, computed } from '@preact/signals';

export const theme = signal<'dark' | 'light'>('dark');
export const lang = signal<'zh' | 'en'>('zh');
export const toasts = signal<{ id: string; message: string; type: string }[]>([]);

/** Safe localStorage wrapper for private browsing / quota errors */
function safeGetItem(key: string): string | null {
  try { return localStorage.getItem(key); } catch { return null; }
}
function safeSetItem(key: string, value: string): void {
  try { localStorage.setItem(key, value); } catch { /* quota/private mode */ }
}

export function initUI() {
  const savedTheme = safeGetItem('oasyce-theme') as 'dark' | 'light' | null;
  const savedLang = safeGetItem('oasyce-lang') as 'zh' | 'en' | null;

  theme.value = savedTheme || (window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
  lang.value = savedLang || (navigator.language?.startsWith('zh') ? 'zh' : 'en');

  document.documentElement.setAttribute('data-theme', theme.value);
}

export function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
  document.documentElement.setAttribute('data-theme', theme.value);
  safeSetItem('oasyce-theme', theme.value);
}

export function toggleLang() {
  lang.value = lang.value === 'zh' ? 'en' : 'zh';
  safeSetItem('oasyce-lang', lang.value);
}

export function showToast(message: string, type = 'info') {
  const id = Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
  toasts.value = [...toasts.value, { id, message, type }];
  setTimeout(() => toasts.value = toasts.value.filter(t => t.id !== id), 3000);
}

const dict: Record<string, Record<string, string>> = {
  zh: {
    home: '首页', mydata: '资产', explore: '市场', auto: '自动化', network: '网络',
    'hero-title-light': '智能的价值',
    'hero-title-bold': '自由交易',
    'hero-sub': '注册数据资产，上架 AI 能力，在去中心化市场中定价、交易、结算。',
    protect: '注册数据', protecting: '注册中...', protected: '已注册',
    'drop-hint': '拖入文件', 'drop-folder': '或文件夹', 'drop-browse': '选择文件',
    'folder-scan-hint': '将扫描此文件夹，发现的资产进入审批队列',
    'describe': '描述', 'describe-hint': '例如：医疗影像、研究数据、创意作品',
    'value': '当前价值', 'owner': '所有者', 'id': '编号',
    'search': '搜索你的数据...', 'no-data': '还没有数据', 'first-data': '注册你的第一份资产，开始参与市场',
    'delete': '移除', 'delete-confirm': '确定移除这份数据？移除后无法恢复。',
    'get-access': '获取访问权', 'quote': '查看报价', 'quoting': '计算中...',
    'pay': '需要支付', 'receive': '获得份额', 'impact': '价格影响',
    'confirm-buy': '确认获取', 'buying': '处理中...', 'back': '返回',
    'paste-id': '粘贴数据编号', 'amount': '金额',
    'identity': '你的身份', 'identity-hint': '这是你在网络上的唯一标识',
    'no-key': '首次注册数据时自动生成', 'copy': '复制', 'copied': '已复制',
    'advanced': '详细信息',
    'again': '继续注册',
    'nav-mydata': '资产', 'nav-mydata-desc': '查看已注册的数据资产',
    'nav-explore': '市场', 'nav-explore-desc': '浏览和交易数据与 AI 能力',
    'nav-network': '网络', 'nav-network-desc': '节点状态与网络信息',
    'cancel': '取消', 'confirm-remove': '确认移除',
    'get-desc': '输入数据编号，查看报价并获取访问权',
    'explore-title': '能力市场',
    'explore-desc': '浏览数据资产与 AI 能力，获取访问权或调用服务',
    'explore-search': '搜索数据编号或描述...',
    'explore-empty': '输入编号或关键词，搜索市场中的资产与能力',
    'categories': '分类',
    'browse-all': '浏览全部',
    'all': '全部',
    'sort-time': '最新', 'sort-value': '价值',
    'load-more': '加载更多', 'no-more': '没有更多了',
    'view-mydata': '查看资产',
    'type-all': '全部', 'type-data': '数据', 'type-capability': '服务',
    'invoke': '调用', 'invoking': '调用中...',
    'invoke-success': '调用成功',
    'provider': '提供者', 'version': '版本',
    'shares-minted': '获得份额',
    'spot-price': '当前价格', 'tags': '标签', 'type': '类型', 'asset-type-data': '数据', 'asset-type-cap': '服务',
    'total-cost': '总花费', 'shares-received': '获得份额', 'price-impact': '价格影响', 'fees': '手续费',
    'creator-fee': '创作者', 'protocol-fee': '协议', 'router-fee': '路由',
    'buy-success': '购买成功', 'new-price': '新价格', 'shares-bought': '购得份额',
    'portfolio': '持仓', 'no-holdings': '暂无持仓', 'avg-price': '均价', 'shares': '份额', 'current-val': '当前价值',
    'stake': '质押', 'staking': '质押中...', 'stake-success': '质押成功',
    'validator': '验证者', 'staked': '已质押', 'reputation': '信誉',
    'validator-id': '验证者 ID', 'stake-amount': '质押金额',
    'no-validators': '暂无验证者',
    'net-hero-light': '连接全球', 'net-hero-bold': '智能市场',
    'net-hero-sub': '运行节点，提供算力，在市场中赚取收益',
    'net-identity': '身份', 'net-node-id': '节点 ID', 'net-pubkey': '公钥', 'net-created': '创建时间',
    'net-show': '显示', 'net-hide': '隐藏',
    'net-chain-height': '链高度', 'net-peers': '已连接节点',
    'net-no-identity': '尚未生成身份', 'net-init-hint': '运行 oasyce start 来初始化节点',
    // AI 算力配置
    'net-ai': 'AI 算力', 'net-ai-desc': '配置你的 AI 能力，为网络提供智能服务并获得 OAS 收益',
    'net-ai-what': '为什么需要 API Key？',
    'net-ai-what-body': '你的节点通过 AI 模型为网络执行任务。你只需要提供一个 API Key（或本地模型地址），Oasyce 会自动调用它来完成工作：',
    'net-ai-use-1': '验证者：AI 自动验证数据质量、检测重复内容、审核元数据合规性',
    'net-ai-use-2': '仲裁者：AI 自动分析争议证据、比对版权信息、生成裁决建议',
    'net-ai-use-3': '你提供算力，网络付你 OAS — 你的 Key 就是你的生产工具',
    'net-ai-supported': '支持的 AI 提供商',
    'net-ai-supported-body': 'Claude (Anthropic)、OpenAI、Ollama (本地)、任意兼容 OpenAI 格式的自定义端点。本地模型无需 API Key，只需填写地址。',
    'net-ai-provider': '选择 AI 提供商',
    'net-ai-key': 'API Key',
    'net-ai-endpoint': '模型地址',
    'net-key-placeholder': '粘贴你的 API Key（sk-... 或 ant-...）',
    'net-key-placeholder-set': '已配置 · 输入新 Key 可覆盖',
    'net-key-save': '保存 Key', 'net-key-update': '更新 Key',
    'net-key-saved': 'API Key 已安全保存',
    'net-key-active': 'AI 已连接',
    'net-key-required': '请先在上方「AI 算力」卡片中配置 API Key',
    'net-endpoint-placeholder': '例如 http://localhost:8080/v1',
    // 节点角色
    'net-role': '节点角色', 'net-role-desc': '配置好 AI 后，选择你在网络中的角色开始赚取收益',
    'net-role-validator': '验证者', 'net-role-arbitrator': '仲裁者',
    'net-role-none': '当前为普通节点。配置 AI 算力后，可以申请成为验证者或仲裁者赚取收益。',
    'net-become-validator': '成为验证者', 'net-become-validator-desc': '质押 OAS + 提供 AI 算力 → 出块赚币',
    'net-become-arbitrator': '成为仲裁者', 'net-become-arbitrator-desc': '提供 AI 算力 → 裁决争议赚币',
    'net-validator-min': '最低质押',
    'net-staked': '已质押',
    'net-role-validator-ok': '验证者注册成功', 'net-role-arbitrator-ok': '仲裁者注册成功',
    'net-val-what': '验证者做什么？',
    'net-val-what-body': '你的 AI 自动完成：打包交易生成区块、验证数据质量（检测伪造/重复）、审核元数据合规性。节点持续运行，无需人工操作。',
    'net-val-earn': '你能赚多少？',
    'net-val-earn-1': '每出一个块获得 4.0 OAS（约每 2 年减半，越早越值钱）',
    'net-val-earn-2': '所有交易手续费的 20% 分给验证者',
    'net-val-earn-3': '质押越多 → 权重越高 → 出块越多 → 赚得越多',
    'net-val-need': '你需要什么？',
    'net-val-need-1': '质押至少 10,000 OAS（锁定期间不可使用）',
    'net-val-need-2': '一个 AI API Key（用于数据质量验证）',
    'net-val-need-3': '节点保持在线 — 长时间离线罚 5%，恶意行为罚 100%，解质押需 28 天',
    'net-arb-what': '仲裁者做什么？',
    'net-arb-what-body': '当有人发起争议（版权纠纷、数据造假等），你的 AI 自动：分析双方证据、比对原始数据指纹、评估版权归属，并生成裁决建议（下架、转移所有权、更正权利等）。',
    'net-arb-earn': '你能赚多少？',
    'net-arb-earn-1': '每次裁决获得仲裁费（由发起方支付，通常 50-500 OAS）',
    'net-arb-earn-2': '裁决越准确 → 信誉越高 → 匹配越多案件 → 赚得越多',
    'net-arb-need': '你需要什么？',
    'net-arb-need-1': '一个 AI API Key（用于证据分析和裁决推理）',
    'net-arb-need-2': '无需质押，但节点需保持在线接收案件',
    'net-arb-tags-hint': '擅长领域（逗号分隔），例如：版权,医疗数据,金融',
    'net-work': '工作收益', 'net-work-desc': '协议自动分配的任务和你的收益统计',
    'net-work-total': '总任务', 'net-work-settled': '已结算',
    'net-work-earned': '累计收益', 'net-work-quality': '平均质量',
    'net-work-failed': '失败', 'net-work-no-tasks': '暂无任务记录',
    'net-work-recent': '最近任务',
    'net-work-type-validation': '验证', 'net-work-type-arbitration': '仲裁',
    'net-work-type-verification': '核实', 'net-work-type-moderation': '审核',
    'net-consensus': '共识状态', 'net-consensus-desc': 'PoS 共识层的 Epoch、Slot 和验证者状态',
    'net-consensus-epoch': '当前 Epoch', 'net-consensus-slot': '当前 Slot',
    'net-consensus-validators': '活跃验证者', 'net-consensus-staked': '总质押',
    'net-consensus-next-epoch': '下一 Epoch', 'net-consensus-delegate': '委托',
    'net-consensus-delegate-desc': '将 OAS 质押给一个验证者',
    'net-consensus-undelegate': '解除委托', 'net-consensus-undelegate-desc': '撤回已委托的 OAS',
    'net-consensus-amount': '金额 (OAS)', 'net-consensus-validator-id': '验证者 ID',
    'net-consensus-submit': '提交', 'net-consensus-submitting': '提交中...',
    'net-watermark': '水印工具', 'net-watermark-desc': '追踪数据在网络中的流转',
    'net-embed': '嵌入水印', 'net-embed-desc': '把身份信息刻进文件',
    'net-extract': '提取水印', 'net-extract-desc': '读出文件的签名信息',
    'net-trace': '追踪分发', 'net-trace-desc': '查看文件的流转记录',
    'identity-card-title': '节点身份',
    'identity-desc': '这是你在 Oasyce 网络上的唯一身份。公钥用于签名交易和验证所有权。',
    'node-id': '节点 ID',
    'created-at': '创建时间',
    'public-key': '公钥',
    'no-identity': '尚未生成身份。运行 oasyce start 来初始化节点。',
    'watermark': '水印工具',
    'wm-embed': '嵌入',
    'wm-extract': '提取',
    'wm-trace': '追踪',
    'wm-file-path': '文件路径',
    'wm-caller-id': '调用者 ID',
    'wm-embed-btn': '嵌入水印',
    'wm-embedding': '嵌入中...',
    'wm-extract-btn': '提取水印',
    'wm-extracting': '提取中...',
    'wm-asset-id': '资产编号',
    'wm-list-btn': '查询分发记录',
    'wm-listing': '查询中...',
    'wm-fingerprint': '指纹',
    'wm-caller': '调用者',
    'wm-timestamp': '时间',
    'wm-watermarked-path': '水印文件',
    'wm-no-records': '暂无分发记录',
    'validators': '验证者',
    'val-staked': '质押量',
    'val-reputation': '信誉',
    'scanner-desc': '扫描本地目录，自动发现可注册的数据资产',
    'automation': '自动化', 'automation-desc': '管理自动注册与交易规则，审批待确认任务',
    'auto-queue': '任务队列', 'auto-rules': '规则设置',
    'pending-tasks': '待确认', 'completed-tasks': '已完成',
    'approve-all': '全部通过', 'all-approved': '已全部通过',
    'queue-empty': '没有待处理任务', 'queue-empty-hint': '扫描目录或等待 Agent 提交新任务',
    'trust-level-desc': '控制 Agent 的自主注册和交易权限',
    'trust-0-desc': '所有操作需手动确认',
    'trust-1-desc': '高置信度自动执行，其余需确认',
    'trust-2-desc': '全部自动执行，仅异常需确认',
    'auto-threshold-desc': '置信度高于阈值的任务将自动通过',
    'threshold-strict': '严格', 'threshold-strict-desc': '仅极高置信度自动通过，大部分需确认',
    'threshold-balanced': '均衡', 'threshold-balanced-desc': '多数可信任务自动通过，可疑任务需确认',
    'threshold-permissive': '宽松', 'threshold-permissive-desc': '大部分任务自动通过，仅低置信度需确认',
    'scan-directory': '扫描目录', 'scan-directory-desc': '扫描本地文件夹，发现可注册的数据资产',
    'agent-executor': '执行 Agent', 'agent-executor-desc': '选择执行注册和交易任务的 Agent',
    'agent-connected': '已连接', 'agent-available': '可用', 'agent-unavailable': '不可用',
    'custom-agent-config': '配置自定义 Agent',
    'custom-agent-name': 'Agent 名称',
    'custom-agent-endpoint': 'API 端点 (例如 https://api.example.com/v1)',
    'custom-agent-test': '测试连接',
    'agent-setup-hint': '需要先在本地安装并配置该 Agent，才能用于自动化任务。',
    'scan-path-hint': '输入目录路径，例如 ~/Documents',
    'scan-btn': '扫描', 'scanning': '扫描中...',
    'scan-done': '扫描完成', 'scan-found': '扫描文件', 'scan-added': '加入收件箱',
    'trust-settings': '信任设置', 'trust-level': '信任等级',
    'trust-0': '手动确认', 'trust-1': '半自动', 'trust-2': '全自动',
    'auto-threshold': '自动确认阈值',
    'inbox': '收件箱', 'inbox-empty': '收件箱为空，扫描目录开始发现资产',
    'inbox-no-match': '没有匹配的项目',
    'filter-all': '全部', 'filter-pending': '待确认', 'filter-approved': '已通过', 'filter-rejected': '已拒绝',
    'confidence': '置信度',
    'status-pending': '待确认', 'status-approved': '已通过', 'status-rejected': '已拒绝',
    'approve': '通过', 'reject': '拒绝', 'edit': '编辑', 'save': '保存',
    'approved': '已通过', 'rejected': '已拒绝', 'saved': '已保存',
    'edit-name': '资产名称', 'edit-tags': '标签（逗号分隔）', 'edit-desc': '描述',
    'rights-type': '权利类型',
    'rights-original': '原创', 'rights-co_creation': '共创', 'rights-licensed': '授权转售', 'rights-collection': '个人收藏',
    'co-creators': '共创者', 'co-creator-address': '地址', 'co-creator-share': '份额 %',
    'add-co-creator': '添加共创者', 'remove-co-creator': '移除',
    'co-creators-hint': '共创至少需要2人，份额合计100%',
    'disputed': '争议中', 'dispute': '发起争议', 'dispute-reason': '争议原因',
    'dispute-confirm': '确认提交', 'dispute-submitting': '提交中...', 'dispute-success': '争议已提交',
    'dispute-reason-hint': '请描述争议原因',
    'arbitrators': '仲裁者', 'arbitrator-score': '匹配度',
    'no-arbitrators': '暂无可用仲裁者', 'arbitrator-auto': '系统自动匹配仲裁者',
    'dispute-status': '争议状态', 'dispute-pending': '待仲裁',
    'drop-folder-hint': '支持拖入文件夹',
    'price-model': '定价方式',
    'price-model-auto': '自动定价', 'price-model-fixed': '固定价格', 'price-model-floor': '保底价格',
    'price-model-auto-desc': '由市场供需自动确定价格',
    'price-model-fixed-desc': '你设定价格，买家按此价购买',
    'price-model-floor-desc': '市场定价，但不低于你设定的底价',
    'price-input': '价格 (OAS)', 'price-input-hint': '输入你期望的价格', 'price-floor-hint': '输入最低价格',
    'register-data': '注册数据', 'publish-cap': '上架能力',
    'cap-name': '名称', 'cap-name-hint': '例如：图像风格迁移',
    'cap-desc-hint': '输入图片，输出指定风格的新图片',
    'cap-desc-guide': '描述输入输出，帮助别人理解如何使用',
    'cap-guide': '将你的 AI 能力上架到市场，供全网发现和调用。',
    'cap-published': '能力已上架',
    'cap-endpoint': '端点 URL', 'cap-endpoint-hint': '例如：https://api.example.com/translate',
    'cap-api-key': 'API Key', 'cap-api-key-hint': '将加密存储，不会暴露给调用者',
    'cap-price': '每次调用价格 (OAS)', 'cap-tags': '标签', 'cap-tags-hint': '逗号分隔，例如：nlp,翻译',
    'cap-rate-limit': '速率限制', 'cap-rate-limit-hint': '每分钟最大调用次数',
    'cap-advanced': '高级设置',
    'my-caps': '我的能力', 'my-data-tab': '数据资产',
    'cap-total-calls': '总调用', 'cap-success-rate': '成功率', 'cap-avg-latency': '平均延迟',
    'cap-earnings': '收益统计', 'cap-total-earned': '总收益',
    'cap-endpoint-url': '端点', 'cap-no-caps': '还没有上架能力',
    'cap-no-caps-hint': '在首页上架你的第一个 AI 能力',
    'cap-invoke-input': '输入 (JSON)', 'cap-invoke-input-hint': '例如：{"text": "hello"}',
    'dispute-resolved': '已裁决', 'dispute-dismissed': '已驳回',
    'remedy-delist': '下架', 'remedy-transfer': '转移所有权', 'remedy-rights_correction': '更正权利类型', 'remedy-share_adjustment': '调整份额',
    'delisted': '已下架',
    'net-retry': '重新检测',
    'files': '个文件',
    'files-bundled': '个文件已打包注册',
    'error-unauthorized': '操作未授权，请刷新页面重试',
    'error-rate-limit': '操作过于频繁，请稍后再试',
    'error-cooldown': '请稍等片刻再购买同一资产',
    'explore-browse': '浏览市场中的数据与 AI 能力',
    'portfolio-hint': '在市场中交易后，持仓将显示在这里',
    'stake-hint': '质押 OAS 到验证者节点，参与网络治理并获得收益',
    'co-creators-sum': '份额合计',
    'removed': '已移除',
    'hash-changed': '已变更',
    're-register': '重新注册',
    'file-missing': '文件丢失',
    'error-generic': '操作失败，请重试',
    'invoke-result': '返回结果',
    'net-consensus-loading': '加载共识数据...',
    // About panel
    'about-version': 'v1.11.0',
    'about-desc': '去中心化 AI 能力自由市场。代理自主注册数据、上架能力、定价交易、结算清分。',
    'about-tab-overview': '概览',
    'about-tab-start': '快速开始',
    'about-tab-arch': '技术架构',
    'about-tab-econ': '经济模型',
    'about-tab-update': '维护更新',
    'about-tab-links': '链接',
    'about-how': 'Oasyce 是一个去中心化的 AI 能力自由市场。数据所有者注册资产并获得加密来源证明 (PoPc)，AI 开发者上架智能服务。代理通过 Recall-Rank 管道发现资产，通过联合曲线自动定价，使用 OAS 代币在托管保护下完成交易结算。',
    'about-quickstart': '1. pip install oasyce\n2. oasyce doctor          # 验证安装\n3. oasyce start           # 启动节点 + 仪表盘\n4. 浏览器打开 http://localhost:8420',
    'about-arch': '核心层级:\n\u2022 Schema Registry \u2014 统一验证 data/capability/oracle/identity 四种资产\n\u2022 引擎管道 \u2014 扫描 \u2192 分类 \u2192 元数据 \u2192 PoPc 证书 \u2192 注册\n\u2022 发现引擎 \u2014 Recall (广召回) \u2192 Rank (信任+经济) + 反馈循环\n\u2022 结算引擎 \u2014 联合曲线定价、托管、份额分配\n\u2022 访问控制 \u2014 L0 元数据 / L1 采样 / L2 计算 / L3 完整\n\u2022 P2P 网络 \u2014 Ed25519 身份、gossip 同步、PoS 共识\n\u2022 风险引擎 \u2014 自动分级 (public / internal / sensitive)',
    'about-econ': '代币: OAS\n\n定价: 联合曲线 (储备率 0.35) \u2014 买家越多价格越高\n份额: 早期买家获利更多 (递减: 100% \u2192 80% \u2192 60% \u2192 40%)\n权利系数: 原创 1.0x / 共创 0.9x / 授权 0.7x / 收藏 0.3x\n质押: 验证者质押 OAS 出块并获得奖励\n区块奖励: 4.0 OAS (主网)，每约 100 万块减半\n托管: 执行前锁定资金，质量验证后释放',
    'about-update': '更新:\n  pip install --upgrade oasyce\n\n从源码构建:\n  git clone https://github.com/Shangri-la-0428/Oasyce_Claw_Plugin_Engine\n  cd Oasyce_Claw_Plugin_Engine && pip install -e .\n\n运行测试:\n  python -m pytest tests/ -v\n\n贡献: Fork \u2192 Branch \u2192 PR (详见 CONTRIBUTING.md)',
    'about-link-intro': '项目介绍',
    'about-link-intro-d': '什么是 Oasyce，为什么重要',
    'about-link-whitepaper': '白皮书',
    'about-link-whitepaper-d': '完整协议设计与经济模型论文',
    'about-link-docs': '协议概览',
    'about-link-docs-d': '技术参考、API 与架构',
    'about-link-github-project': 'GitHub (项目)',
    'about-link-github-project-d': '规范、文档与路线图',
    'about-link-github-engine': 'GitHub (引擎)',
    'about-link-github-engine-d': '插件引擎源代码',
    'about-link-discord': 'Discord 社区',
    'about-link-discord-d': '聊天、支持与治理',
    'about-link-contact': '联系我们',
    // Agent Scheduler
    'agent-schedule': '定时任务', 'agent-schedule-desc': '让插件自主运行，定时扫描、注册和交易',
    'agent-enabled': '启用定时任务', 'agent-disabled': '已停用',
    'agent-running': '运行中', 'agent-interval': '执行间隔', 'agent-interval-hours': '小时',
    'agent-scan-paths': '扫描目录', 'agent-scan-paths-hint': '每行一个目录路径',
    'agent-auto-register': '自动注册', 'agent-auto-trade': '自动交易',
    'agent-auto-trade-desc': '自动购买匹配标签的能力',
    'agent-trade-tags': '交易标签', 'agent-trade-tags-hint': '逗号分隔，如 nlp,translation',
    'agent-trade-max': '单次最大花费',
    'agent-last-run': '上次执行', 'agent-next-run': '下次执行',
    'agent-total-runs': '总执行次数', 'agent-total-registered': '总注册数', 'agent-total-errors': '总错误数',
    'agent-run-now': '立即执行', 'agent-history': '执行历史',
    'agent-save-config': '保存配置', 'agent-no-history': '暂无执行记录',
  },
  en: {
    home: 'Home', mydata: 'My Data', explore: 'Market', auto: 'Automation', network: 'Network',
    'hero-title-light': 'Intelligence has',
    'hero-title-bold': 'a price.',
    'hero-sub': 'Register data assets. List AI capabilities. Price, trade, and settle in a decentralized market.',
    protect: 'Register', protecting: 'Registering...', protected: 'Registered',
    'drop-hint': 'Drop file', 'drop-folder': 'or folder', 'drop-browse': 'choose file',
    'folder-scan-hint': 'This folder will be scanned. Discovered assets go to the approval queue.',
    'describe': 'Description', 'describe-hint': 'e.g. medical imaging, research data, creative work',
    'value': 'Value', 'owner': 'Owner', 'id': 'ID',
    'search': 'Search your data...', 'no-data': 'No data yet', 'first-data': 'Register your first asset to join the market',
    'delete': 'Remove', 'delete-confirm': 'Remove this data? This cannot be undone.',
    'get-access': 'Get access', 'quote': 'Get quote', 'quoting': 'Calculating...',
    'pay': 'You pay', 'receive': 'You receive', 'impact': 'Price impact',
    'confirm-buy': 'Confirm', 'buying': 'Processing...', 'back': 'Back',
    'paste-id': 'Paste data ID', 'amount': 'Amount',
    'identity': 'Your identity', 'identity-hint': 'Your unique ID on the network',
    'no-key': 'Auto-generated on first registration', 'copy': 'Copy', 'copied': 'Copied',
    'advanced': 'Details',
    'again': 'Register another',
    'nav-mydata': 'My data', 'nav-mydata-desc': 'View your registered data assets',
    'nav-explore': 'Market', 'nav-explore-desc': 'Browse and trade data & AI capabilities',
    'nav-network': 'Network', 'nav-network-desc': 'Node status and network info',
    'cancel': 'Cancel', 'confirm-remove': 'Confirm remove',
    'get-desc': 'Enter a data ID to get a quote and gain access',
    'explore-title': 'Capability Market',
    'explore-desc': 'Browse data assets and AI capabilities. Get access or invoke services.',
    'explore-search': 'Search by ID or description...',
    'explore-empty': 'Search the market by ID or keyword',
    'categories': 'Categories',
    'browse-all': 'Browse all',
    'all': 'All',
    'sort-time': 'Latest', 'sort-value': 'Value',
    'load-more': 'Load more', 'no-more': "That's all",
    'view-mydata': 'View my data',
    'type-all': 'All', 'type-data': 'Data', 'type-capability': 'Services',
    'invoke': 'Invoke', 'invoking': 'Invoking...',
    'invoke-success': 'Invoked successfully',
    'provider': 'Provider', 'version': 'Version',
    'shares-minted': 'Shares minted',
    'spot-price': 'Spot price', 'tags': 'Tags', 'type': 'Type', 'asset-type-data': 'Data', 'asset-type-cap': 'Service',
    'total-cost': 'Total cost', 'shares-received': 'Shares received', 'price-impact': 'Price impact', 'fees': 'Fees',
    'creator-fee': 'Creator', 'protocol-fee': 'Protocol', 'router-fee': 'Router',
    'buy-success': 'Purchase successful', 'new-price': 'New price', 'shares-bought': 'Shares bought',
    'portfolio': 'Portfolio', 'no-holdings': 'No holdings yet', 'avg-price': 'Avg price', 'shares': 'Shares', 'current-val': 'Current value',
    'stake': 'Stake', 'staking': 'Staking...', 'stake-success': 'Staked successfully',
    'validator': 'Validator', 'staked': 'Staked', 'reputation': 'Reputation',
    'validator-id': 'Validator ID', 'stake-amount': 'Stake amount',
    'no-validators': 'No validators yet',
    'net-hero-light': 'Connected to the', 'net-hero-bold': 'intelligence market.',
    'net-hero-sub': 'Run a node, contribute compute, earn from the market.',
    'net-identity': 'IDENTITY', 'net-node-id': 'Node ID', 'net-pubkey': 'Public Key', 'net-created': 'Created',
    'net-show': 'Show', 'net-hide': 'Hide',
    'net-chain-height': 'Chain height', 'net-peers': 'Connected peers',
    'net-no-identity': 'No identity yet', 'net-init-hint': 'Run oasyce start to initialize your node',
    // AI compute config
    'net-ai': 'AI COMPUTE', 'net-ai-desc': 'Configure your AI capability to provide intelligence to the network and earn OAS',
    'net-ai-what': 'Why do I need an API Key?',
    'net-ai-what-body': 'Your node uses an AI model to perform tasks for the network. Just provide an API Key (or local model address) and Oasyce handles the rest:',
    'net-ai-use-1': 'Validators: AI auto-verifies data quality, detects duplicates, audits metadata compliance',
    'net-ai-use-2': 'Arbitrators: AI auto-analyzes dispute evidence, compares copyright info, generates rulings',
    'net-ai-use-3': 'You provide compute, the network pays you OAS — your Key is your production tool',
    'net-ai-supported': 'Supported AI providers',
    'net-ai-supported-body': 'Claude (Anthropic), OpenAI, Ollama (local), or any OpenAI-compatible custom endpoint. Local models need no API Key — just enter the address.',
    'net-ai-provider': 'AI Provider',
    'net-ai-key': 'API Key',
    'net-ai-endpoint': 'Model Endpoint',
    'net-key-placeholder': 'Paste your API Key (sk-... or ant-...)',
    'net-key-placeholder-set': 'Configured · enter a new key to replace',
    'net-key-save': 'Save Key', 'net-key-update': 'Update Key',
    'net-key-saved': 'API Key saved securely',
    'net-key-active': 'AI Connected',
    'net-key-required': 'Please configure your API Key in the AI Compute card above first',
    'net-endpoint-placeholder': 'e.g. http://localhost:8080/v1',
    // Node role
    'net-role': 'NODE ROLE', 'net-role-desc': 'Once AI is configured, choose your role to start earning',
    'net-role-validator': 'Validator', 'net-role-arbitrator': 'Arbitrator',
    'net-role-none': 'Standard peer node. Configure AI compute above, then apply as validator or arbitrator to earn OAS.',
    'net-become-validator': 'Become Validator', 'net-become-validator-desc': 'Stake OAS + provide AI compute → produce blocks, earn tokens',
    'net-become-arbitrator': 'Become Arbitrator', 'net-become-arbitrator-desc': 'Provide AI compute → resolve disputes, earn fees',
    'net-validator-min': 'Minimum stake',
    'net-staked': 'Staked',
    'net-role-validator-ok': 'Registered as validator', 'net-role-arbitrator-ok': 'Registered as arbitrator',
    'net-val-what': 'What does your node do?',
    'net-val-what-body': 'Your AI automatically: bundles transactions into blocks, verifies data quality (detects forgery/duplicates), audits metadata compliance. Runs continuously, no manual work needed.',
    'net-val-earn': 'How much can you earn?',
    'net-val-earn-1': '4.0 OAS per block produced (halves ~every 2 years — earlier is more valuable)',
    'net-val-earn-2': '20% of all transaction fees go to validators',
    'net-val-earn-3': 'More stake → higher weight → more blocks → more earnings',
    'net-val-need': 'What do you need?',
    'net-val-need-1': 'Stake at least 10,000 OAS (locked while staking)',
    'net-val-need-2': 'An AI API Key (for data quality verification)',
    'net-val-need-3': 'Keep your node online — offline: 5% slash, malicious: 100% slash, unstaking: 28-day cooldown',
    'net-arb-what': 'What does your node do?',
    'net-arb-what-body': 'When a dispute is filed (copyright, fraud, etc.), your AI automatically: analyzes both sides\' evidence, compares data fingerprints, evaluates ownership claims, and generates a ruling recommendation (delist, transfer, correct rights, etc.).',
    'net-arb-earn': 'How much can you earn?',
    'net-arb-earn-1': 'Arbitration fee per ruling (paid by disputing party, typically 50-500 OAS)',
    'net-arb-earn-2': 'More accurate rulings → higher reputation → more cases → more earnings',
    'net-arb-need': 'What do you need?',
    'net-arb-need-1': 'An AI API Key (for evidence analysis and reasoning)',
    'net-arb-need-2': 'No staking required, but keep your node online to receive cases',
    'net-arb-tags-hint': 'Expertise areas (comma-separated), e.g. copyright,medical,finance',
    'net-work': 'WORK EARNINGS', 'net-work-desc': 'Protocol-assigned tasks and your earnings summary',
    'net-work-total': 'Total tasks', 'net-work-settled': 'Settled',
    'net-work-earned': 'Total earned', 'net-work-quality': 'Avg quality',
    'net-work-failed': 'Failed', 'net-work-no-tasks': 'No task history yet',
    'net-work-recent': 'Recent tasks',
    'net-work-type-validation': 'Validation', 'net-work-type-arbitration': 'Arbitration',
    'net-work-type-verification': 'Verification', 'net-work-type-moderation': 'Moderation',
    'net-consensus': 'CONSENSUS STATUS', 'net-consensus-desc': 'PoS consensus layer epoch, slot, and validator status',
    'net-consensus-epoch': 'Current Epoch', 'net-consensus-slot': 'Current Slot',
    'net-consensus-validators': 'Active Validators', 'net-consensus-staked': 'Total Staked',
    'net-consensus-next-epoch': 'Next Epoch', 'net-consensus-delegate': 'Delegate',
    'net-consensus-delegate-desc': 'Stake OAS to a validator',
    'net-consensus-undelegate': 'Undelegate', 'net-consensus-undelegate-desc': 'Withdraw staked OAS',
    'net-consensus-amount': 'Amount (OAS)', 'net-consensus-validator-id': 'Validator ID',
    'net-consensus-submit': 'Submit', 'net-consensus-submitting': 'Submitting...',
    'net-watermark': 'WATERMARK TOOLS', 'net-watermark-desc': 'Track data distribution across the network',
    'net-embed': 'Embed watermark', 'net-embed-desc': 'Sign your identity into a file',
    'net-extract': 'Extract watermark', 'net-extract-desc': 'Read signature info from a file',
    'net-trace': 'Trace distribution', 'net-trace-desc': 'View file distribution history',
    'identity-card-title': 'Node Identity',
    'identity-desc': 'This is your unique identity on the Oasyce network. Your public key is used to sign transactions and verify ownership.',
    'node-id': 'Node ID',
    'created-at': 'Created',
    'public-key': 'Public Key',
    'no-identity': 'No identity yet. Run oasyce start to initialize your node.',
    'watermark': 'Watermark Tools',
    'wm-embed': 'Embed',
    'wm-extract': 'Extract',
    'wm-trace': 'Trace',
    'wm-file-path': 'File path',
    'wm-caller-id': 'Caller ID',
    'wm-embed-btn': 'Embed watermark',
    'wm-embedding': 'Embedding...',
    'wm-extract-btn': 'Extract watermark',
    'wm-extracting': 'Extracting...',
    'wm-asset-id': 'Asset ID',
    'wm-list-btn': 'List distributions',
    'wm-listing': 'Loading...',
    'wm-fingerprint': 'Fingerprint',
    'wm-caller': 'Caller',
    'wm-timestamp': 'Time',
    'wm-watermarked-path': 'Watermarked file',
    'wm-no-records': 'No distribution records',
    'validators': 'Validators',
    'val-staked': 'Staked',
    'val-reputation': 'Reputation',
    'scanner-desc': 'Scan local directories to discover registerable data assets',
    'automation': 'Automation', 'automation-desc': 'Manage auto-registration and trading rules, review pending tasks',
    'auto-queue': 'Queue', 'auto-rules': 'Rules',
    'pending-tasks': 'Pending', 'completed-tasks': 'Completed',
    'approve-all': 'Approve all', 'all-approved': 'All approved',
    'queue-empty': 'No pending tasks', 'queue-empty-hint': 'Scan a directory or wait for agents to submit tasks',
    'trust-level-desc': 'Control how much autonomy agents have for registration and trading',
    'trust-0-desc': 'All actions require manual approval',
    'trust-1-desc': 'High-confidence actions auto-execute, rest need approval',
    'trust-2-desc': 'All actions auto-execute, only anomalies flagged',
    'auto-threshold-desc': 'Tasks above the threshold are auto-approved',
    'threshold-strict': 'Strict', 'threshold-strict-desc': 'Only very high confidence auto-approved, most need review',
    'threshold-balanced': 'Balanced', 'threshold-balanced-desc': 'Most trusted tasks auto-approved, suspicious ones flagged',
    'threshold-permissive': 'Permissive', 'threshold-permissive-desc': 'Most tasks auto-approved, only low confidence flagged',
    'scan-directory': 'Scan Directory', 'scan-directory-desc': 'Scan local folders to discover registerable data assets',
    'agent-executor': 'Agent Executor', 'agent-executor-desc': 'Choose which agent handles registration and trading tasks',
    'agent-connected': 'Connected', 'agent-available': 'Available', 'agent-unavailable': 'Unavailable',
    'custom-agent-config': 'Configure Custom Agent',
    'custom-agent-name': 'Agent name',
    'custom-agent-endpoint': 'API endpoint (e.g. https://api.example.com/v1)',
    'custom-agent-test': 'Test connection',
    'agent-setup-hint': 'Install and configure this agent locally before using it for automation.',
    'scan-path-hint': 'Enter directory path, e.g. ~/Documents',
    'scan-btn': 'Scan', 'scanning': 'Scanning...',
    'scan-done': 'Scan complete', 'scan-found': 'Files scanned', 'scan-added': 'Added to inbox',
    'trust-settings': 'Trust Settings', 'trust-level': 'Trust Level',
    'trust-0': 'Manual', 'trust-1': 'Semi-auto', 'trust-2': 'Full-auto',
    'auto-threshold': 'Auto-approve threshold',
    'inbox': 'Inbox', 'inbox-empty': 'Inbox empty. Scan a directory to discover assets.',
    'inbox-no-match': 'No matching items',
    'filter-all': 'All', 'filter-pending': 'Pending', 'filter-approved': 'Approved', 'filter-rejected': 'Rejected',
    'confidence': 'Confidence',
    'status-pending': 'Pending', 'status-approved': 'Approved', 'status-rejected': 'Rejected',
    'approve': 'Approve', 'reject': 'Reject', 'edit': 'Edit', 'save': 'Save',
    'approved': 'Approved', 'rejected': 'Rejected', 'saved': 'Saved',
    'edit-name': 'Asset name', 'edit-tags': 'Tags (comma separated)', 'edit-desc': 'Description',
    'rights-type': 'Rights type',
    'rights-original': 'Original', 'rights-co_creation': 'Co-creation', 'rights-licensed': 'Licensed resale', 'rights-collection': 'Personal collection',
    'co-creators': 'Co-creators', 'co-creator-address': 'Address', 'co-creator-share': 'Share %',
    'add-co-creator': 'Add co-creator', 'remove-co-creator': 'Remove',
    'co-creators-hint': 'Co-creation requires at least 2 people, shares must total 100%',
    'disputed': 'Disputed', 'dispute': 'Dispute', 'dispute-reason': 'Dispute reason',
    'dispute-confirm': 'Submit', 'dispute-submitting': 'Submitting...', 'dispute-success': 'Dispute submitted',
    'dispute-reason-hint': 'Describe the reason for dispute',
    'arbitrators': 'Arbitrators', 'arbitrator-score': 'Match',
    'no-arbitrators': 'No arbitrators available', 'arbitrator-auto': 'System auto-matches arbitrators',
    'dispute-status': 'Dispute status', 'dispute-pending': 'Pending arbitration',
    'drop-folder-hint': 'Supports folder drag-and-drop',
    'price-model': 'Pricing Model',
    'price-model-auto': 'Auto (Bonding Curve)', 'price-model-fixed': 'Fixed Price', 'price-model-floor': 'Floor Price',
    'price-model-auto-desc': 'Price determined by market supply and demand',
    'price-model-fixed-desc': 'You set the price, buyers pay this amount',
    'price-model-floor-desc': 'Market pricing, but never below your floor',
    'price-input': 'Price (OAS)', 'price-input-hint': 'Enter your desired price', 'price-floor-hint': 'Enter minimum price',
    'register-data': 'Register data', 'publish-cap': 'List capability',
    'cap-name': 'Name', 'cap-name-hint': 'e.g. Image style transfer',
    'cap-desc-hint': 'Input image, output restyled image',
    'cap-desc-guide': 'Describe inputs and outputs so others know how to use it',
    'cap-guide': 'List your AI capability on the market. Others can discover and invoke it.',
    'cap-published': 'Capability listed',
    'cap-endpoint': 'Endpoint URL', 'cap-endpoint-hint': 'e.g. https://api.example.com/translate',
    'cap-api-key': 'API Key', 'cap-api-key-hint': 'Encrypted at rest, never exposed to consumers',
    'cap-price': 'Price per call (OAS)', 'cap-tags': 'Tags', 'cap-tags-hint': 'Comma-separated, e.g. nlp,translation',
    'cap-rate-limit': 'Rate limit', 'cap-rate-limit-hint': 'Max calls per minute',
    'cap-advanced': 'Advanced',
    'my-caps': 'My Capabilities', 'my-data-tab': 'Data Assets',
    'cap-total-calls': 'Total calls', 'cap-success-rate': 'Success rate', 'cap-avg-latency': 'Avg latency',
    'cap-earnings': 'Earnings', 'cap-total-earned': 'Total earned',
    'cap-endpoint-url': 'Endpoint', 'cap-no-caps': 'No capabilities listed yet',
    'cap-no-caps-hint': 'List your first AI capability from the Home page',
    'cap-invoke-input': 'Input (JSON)', 'cap-invoke-input-hint': 'e.g. {"text": "hello"}',
    'dispute-resolved': 'Resolved', 'dispute-dismissed': 'Dismissed',
    'remedy-delist': 'Delist', 'remedy-transfer': 'Transfer ownership', 'remedy-rights_correction': 'Correct rights type', 'remedy-share_adjustment': 'Adjust shares',
    'delisted': 'Delisted',
    'net-retry': 'Retry',
    'files': 'files',
    'files-bundled': 'files bundled and registered',
    'error-unauthorized': 'Unauthorized. Please refresh the page.',
    'error-rate-limit': 'Too many requests. Please wait.',
    'error-cooldown': 'Please wait before buying the same asset again',
    'explore-browse': 'Browse and trade data & AI capabilities',
    'portfolio-hint': 'Trade on the Market tab to see your holdings here',
    'stake-hint': 'Stake OAS to validator nodes to participate in governance and earn rewards',
    'co-creators-sum': 'Total shares',
    'removed': 'Removed',
    'hash-changed': 'Changed',
    're-register': 'Re-register',
    'file-missing': 'File missing',
    'error-generic': 'Something went wrong. Please try again.',
    'invoke-result': 'Result',
    'net-consensus-loading': 'Loading consensus data...',
    // About panel
    'about-version': 'v1.11.0',
    'about-desc': 'Decentralized AI capability marketplace. Agents register data, list capabilities, price, trade, and settle autonomously.',
    'about-tab-overview': 'Overview',
    'about-tab-start': 'Quick Start',
    'about-tab-arch': 'Architecture',
    'about-tab-econ': 'Economics',
    'about-tab-update': 'Maintain',
    'about-tab-links': 'Links',
    'about-how': 'Oasyce is a decentralized AI capability marketplace. Data owners register assets and receive a cryptographic proof-of-provenance certificate (PoPc). AI developers list intelligent services. Agents discover assets via a Recall-Rank pipeline, auto-price through bonding curves, and settle transactions with escrow-protected OAS tokens.',
    'about-quickstart': '1. pip install oasyce\n2. oasyce doctor          # verify setup\n3. oasyce start           # launch node + dashboard\n4. Open http://localhost:8420',
    'about-arch': 'Core Layers:\n\u2022 Schema Registry \u2014 unified validation for data/capability/oracle/identity\n\u2022 Engine Pipeline \u2014 Scan \u2192 Classify \u2192 Metadata \u2192 PoPc Certificate \u2192 Register\n\u2022 Discovery \u2014 Recall (broad retrieval) \u2192 Rank (trust + economics) + feedback loop\n\u2022 Settlement \u2014 bonding curve pricing, escrow, share distribution\n\u2022 Access Control \u2014 L0 metadata / L1 sample / L2 compute / L3 full\n\u2022 P2P Network \u2014 Ed25519 identity, gossip sync, PoS consensus\n\u2022 Risk Engine \u2014 auto-classification (public / internal / sensitive)',
    'about-econ': 'Token: OAS\n\nPricing: Bonding curve (reserve ratio 0.35) \u2014 more buyers = higher price\nShares: Early buyers earn more (diminishing: 100% \u2192 80% \u2192 60% \u2192 40%)\nRights multiplier: original 1.0x / co_creation 0.9x / licensed 0.7x / collection 0.3x\nStaking: Validators stake OAS to produce blocks and earn rewards\nBlock reward: 4.0 OAS (mainnet), halving every ~1M blocks\nEscrow: Funds locked before execution, released after quality verification',
    'about-update': 'Update:\n  pip install --upgrade oasyce\n\nBuild from source:\n  git clone https://github.com/Shangri-la-0428/Oasyce_Claw_Plugin_Engine\n  cd Oasyce_Claw_Plugin_Engine && pip install -e .\n\nRun tests:\n  python -m pytest tests/ -v\n\nContribute: Fork \u2192 Branch \u2192 PR (see CONTRIBUTING.md)',
    'about-link-intro': 'Introduction',
    'about-link-intro-d': 'What is Oasyce and why it matters',
    'about-link-whitepaper': 'Whitepaper',
    'about-link-whitepaper-d': 'Full protocol design and economics paper',
    'about-link-docs': 'Protocol Overview',
    'about-link-docs-d': 'Technical reference, API, and architecture',
    'about-link-github-project': 'GitHub (Project)',
    'about-link-github-project-d': 'Specs, docs, and roadmap',
    'about-link-github-engine': 'GitHub (Engine)',
    'about-link-github-engine-d': 'Plugin engine source code',
    'about-link-discord': 'Discord Community',
    'about-link-discord-d': 'Chat, support, and governance',
    'about-link-contact': 'Contact',
    // Agent Scheduler
    'agent-schedule': 'Scheduled Tasks', 'agent-schedule-desc': 'Let the plugin run autonomously — scan, register, and trade on schedule',
    'agent-enabled': 'Enable Scheduler', 'agent-disabled': 'Disabled',
    'agent-running': 'Running', 'agent-interval': 'Interval', 'agent-interval-hours': 'hours',
    'agent-scan-paths': 'Scan Directories', 'agent-scan-paths-hint': 'One directory path per line',
    'agent-auto-register': 'Auto Register', 'agent-auto-trade': 'Auto Trade',
    'agent-auto-trade-desc': 'Auto-buy capabilities matching tags',
    'agent-trade-tags': 'Trade Tags', 'agent-trade-tags-hint': 'Comma-separated, e.g. nlp,translation',
    'agent-trade-max': 'Max Spend Per Cycle',
    'agent-last-run': 'Last Run', 'agent-next-run': 'Next Run',
    'agent-total-runs': 'Total Runs', 'agent-total-registered': 'Total Registered', 'agent-total-errors': 'Total Errors',
    'agent-run-now': 'Run Now', 'agent-history': 'Run History',
    'agent-save-config': 'Save Config', 'agent-no-history': 'No runs yet',
  },
};

/**
 * i18n computed — 返回一个 Proxy 包裹的 dict
 * 组件里用 i18n.value['key'] 来读取，确保 signal tracking
 * 如果 key 不存在，返回 fallback 链：当前语言 → en → key 本身
 * 这样即使翻译缺失也不会渲染 undefined
 */
export const i18n = computed(() => {
  const current = dict[lang.value] || dict['en'];
  const fallback = dict['en'];
  return new Proxy(current, {
    get(target, prop: string) {
      return target[prop] ?? fallback[prop] ?? prop;
    },
  });
});
